services:
  - type: web
    name: nexuspos
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from database import Database; db = Database(); db.crear_tablas()"
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: e8a521dd52efc86130c0c1392c5dc759
      - key: RENDER_API_KEY
        value: rnd_gr1Dc5
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: sqlite:///nexuspos.db 